apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: db
    pod-template-hash: 647d795b7b
  name: db
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: db-deployment
    pod-template-hash: 647d795b7b
status:
  loadBalancer: {}